### ISSUE TITLE
Дебаг норм собирается, при попытке собрать релиз кидает ошибку.

### ISSUE THREAD

**Issue by VadimOsovsky** [ObjReponse/flutter_vk_login#4]
MacBook-Pro-Vadim:vk_mobile_flutter vadim$ flutter run --release
Initializing gradle...                                              1.4s
Resolving dependencies...                                           2.9s
Launching lib/main.dart on MI 8 in release mode...
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':flutter_vk_login:verifyReleaseResources'.   
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  Output:  /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/merged/release/values/values.xml:201: error: resource android:attr/fontVariationSettings not found.
  /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/merged/release/values/values.xml:202: error: resource android:attr/ttcIndex not found.
  error: failed linking references.                                     
                                                                        
  Command: /Users/vadim/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-osx.jar/8562978d6c647d4eb837a95f4dfd0ee5/aapt2-3.2.1-4818971-osx/aapt2 link -I\
          /Users/vadim/Library/Android/sdk/platforms/android-27/android.jar\
          --manifest\                                                   
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/aapt_friendly_merged_manifests/release/processReleaseManifest/aapt/AndroidManifest.xml\
          -o\                                                           
          /var/folders/ql/c1txz_750m33f40jdqd_xdrm0000gn/T/aapt-2744467850460209808-out\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/layout_notification_action_tombstone.xml.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-ur_values-ur.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable_notification_icon_background.xml.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-pa_values-pa.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-pt-rBR_values-pt-rBR.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-as_values-as.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-fi_values-fi.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable_vk_share_send_button_background.xml.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-uk_values-uk.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/layout_notification_template_big_media_narrow_custom.xml.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/layout_notification_template_part_time.xml.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-ka_values-ka.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-iw_values-iw.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable-mdpi-v4_notify_panel_notification_icon_bg.png.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-bs_values-bs.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-mk_values-mk.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable_notification_bg_low.xml.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-in_values-in.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-zu_values-zu.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-mr_values-mr.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable-xhdpi-v4_notification_bg_low_normal.9.png.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-hr_values-hr.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-en-rAU_values-en-rAU.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-sk_values-sk.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/layout_notification_action.xml.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable-v21_notification_action_background.xml.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-th_values-th.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-sr_values-sr.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-km_values-km.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-af_values-af.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-pt_values-pt.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-es-rUS_values-es-rUS.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-v11_values-v11.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-fr-rCA_values-fr-rCA.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable_vk_clear_shape.xml.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable-xhdpi-v4_ic_close_white_24dp.png.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-gl_values-gl.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/layout-v21_notification_action_tombstone.xml.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-gu_values-gu.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-kk_values-kk.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/layout_notification_template_media_custom.xml.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-zh-rHK_values-zh-rHK.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/layout_vk_captcha_dialog.xml.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-te_values-te.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/layout_notification_template_big_media_narrow.xml.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/layout_notification_template_media.xml.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/layout_vk_open_auth_dialog.xml.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-ml_values-ml.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-ky_values-ky.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-ar_values-ar.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable-xhdpi-v4_notify_panel_notification_icon_bg.png.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/layout_notification_template_lines_media.xml.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-en-rIN_values-en-rIN.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-da_values-da.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/layout_notification_media_cancel_action.xml.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-am_values-am.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-ms_values-ms.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-zh-rTW_values-zh-rTW.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable-xxxhdpi-v4_ic_ab_app.png.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable-xxhdpi-v4_bg_toolbar_shadow_dark.png.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-en-rGB_values-en-rGB.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/layout_notification_media_action.xml.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-w600dp-v13_values-w600dp-v13.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-hy_values-hy.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-zh-rCN_values-zh-rCN.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-nl_values-nl.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/layout_notification_template_part_chronometer.xml.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-ro_values-ro.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/layout-v21_notification_template_icon_group.xml.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-my_values-my.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-lv_values-lv.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-pl_values-pl.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable-hdpi-v4_ic_close_white_24dp.png.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable-xxhdpi-v4_ic_ab_app.png.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-lo_values-lo.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable-xxxhdpi-v4_bg_toolbar_shadow_dark.png.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/layout_notification_template_big_media.xml.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values_values.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-bg_values-bg.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-sl_values-sl.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-v21_values-v21.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-en-rCA_values-en-rCA.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-hu_values-hu.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable-hdpi-v4_ic_ab_app.png.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-vi_values-vi.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-en-rXC_values-en-rXC.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-ru_values-ru.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/layout-v21_notification_template_custom_big.xml.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable-hdpi-v4_notification_bg_normal.9.png.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-pt-rPT_values-pt-rPT.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-fr_values-fr.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable-mdpi-v4_ic_close_white_24dp.png.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-v24_values-v24.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-et_values-et.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-bn_values-bn.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-ca_values-ca.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable-xhdpi-v4_notification_bg_low_pressed.9.png.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-is_values-is.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable-xhdpi-v4_bg_toolbar_shadow_dark.png.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable-hdpi-v4_notification_bg_normal_pressed.9.png.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-sv_values-sv.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-tl_values-tl.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/layout_notification_template_icon_group.xml.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-fa_values-fa.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-uz_values-uz.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-ko_values-ko.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable-hdpi-v4_notify_panel_notification_icon_bg.png.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-hi_values-hi.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable-mdpi-v4_notification_bg_normal_pressed.9.png.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-b+sr+Latn_values-b+sr+Latn.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable-xhdpi-v4_notification_bg_normal.9.png.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-si_values-si.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-ne_values-ne.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-it_values-it.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-de_values-de.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/layout-v21_notification_action.xml.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-ta_values-ta.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/layout-v16_vk_share_dialog.xml.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-es_values-es.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/layout_notification_template_big_media_custom.xml.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable_notification_bg.xml.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-el_values-el.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable-hdpi-v4_notification_bg_low_pressed.9.png.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable-xxhdpi-v4_ic_close_white_24dp.png.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-mn_values-mn.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/layout-v16_notification_template_custom_big.xml.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-eu_values-eu.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable_notification_tile_bg.xml.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-cs_values-cs.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable-xxxhdpi-v4_ic_close_white_24dp.png.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-nb_values-nb.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable-mdpi-v4_notification_bg_low_normal.9.png.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-az_values-az.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-v16_values-v16.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable-mdpi-v4_ic_ab_app.png.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-be_values-be.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-w720dp-v13_values-w720dp-v13.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-sw_values-sw.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable-mdpi-v4_notification_bg_normal.9.png.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable-hdpi-v4_bg_toolbar_shadow_dark.png.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable-xhdpi-v4_ic_ab_app.png.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-tr_values-tr.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable-mdpi-v4_notification_bg_low_pressed.9.png.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-or_values-or.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable_vk_gray_transparent_shape.xml.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-sq_values-sq.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-kn_values-kn.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable-mdpi-v4_bg_toolbar_shadow_dark.png.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-lt_values-lt.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable-hdpi-v4_notification_bg_low_normal.9.png.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/values-ja_values-ja.arsc.flat\
          -R\                                                           
          /Users/vadim/Desktop/Projects/vk_mobile_flutter/build/flutter_vk_login/intermediates/res/compiled/release/drawable-xhdpi-v4_notification_bg_normal_pressed.9.png.flat\
          --auto-add-overlay\                                           
          --non-final-ids\                                              
          -0\                                                           
          apk\                                                          
          --no-version-vectors                                          
  Daemon:  AAPT2 aapt2-3.2.1-4818971-osx Daemon #0                      
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 5s                                                      
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                       6.5s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleRelease failed with exit code 1

**Comment by ObjReponse** [comment]
Привет. Беглый осмотр xml-ек показал что в плагине, таких атрибутов нет и не было в общем-то. Хоть я и не настоящий сварщик, но возможно вам стоит проверить свой остальной проект.

**Comment by VadimOsovsky** [comment]
@ObjReponse а есть предложения на предмет чего мне нужно проверить остальной проект, и почему это именно на релизе происходит?

**Comment by ObjReponse** [comment]
Ха, а поиск по ошибке показал вот такое:
[Problem Isolated - Need Solution. Failed Build: ':app:processArm64DebugResources' attr/ttcIndex attr/fontVariationSettings #205](https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview/issues/205#issuecomment-371669478)
Надо плагин переводить на новую версию андроид саппорт

**Comment by ObjReponse** [comment]
Так что виноват плагин. И решение тут либо Вам понижать версию андроида, либо мне переходить на поддержку новой версии андроидсаппорт.

**Comment by VadimOsovsky** [comment]
`переходить на поддержку новой версии андроидсаппорт.` было бы круто!
