### ISSUE TITLE
SDK not set up, check application settings

### ISSUE THREAD

**Issue by denid88** [ObjReponse/flutter_vk_login#5]
My device Android 9 Samsung J6 show me next error:
**{"error": "invalid_request", "error_description": "sdk_not set up", check application settings}**

My device Android 6 work correctly!
But in other device with Android 9 Honor X8  its work correctly

**Problem**: another native vk app installed.

![снимок_1](https://user-images.githubusercontent.com/46416970/68296091-6fdeec00-009c-11ea-9459-06a5a22969c8.png)

**Comment by giaotuancse** [comment]
same issue, have you found solution @denid88 ?

**Comment by denid88** [comment]
> same issue, have you found solution @denid88 ?
we cancelled solution vk auth in project because we needed ios auth also
